#### IMPORTING THE LIBRARIES

In [2]:
import pandas as pd
import numpy as np

### LOADING THE DATASET IN A NEW OBJECT CALLED FAKE

In [3]:
fake=pd.read_csv("news.csv")

### DISPLAYING THE COLUMNS IN THE DATASET

In [4]:
fake.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

### DROPPING A COLUMN ALONG WITH THE MISSING VALUES

In [5]:
fake = fake.drop(['Unnamed: 0'],axis=1)
fake = fake.dropna()

### DISPLAYING THE DATASET AFTER DROPING THE COLUMN

In [6]:
fake.head()

title  \
0                       You Can Smell Hillary’s Fear   
1  Watch The Exact Moment Paul Ryan Committed Pol...   
2        Kerry to go to Paris in gesture of sympathy   
3  Bernie supporters on Twitter erupt in anger ag...   
4   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

### EXTRACTING FIRST 1000 VALUES IN THE DATA TO BUILD THE MODEL

In [7]:
fake = fake[0:1000]

### DISPLAYING THE FIRST 1000 VALUES

In [8]:
fake

title  \
0                         You Can Smell Hillary’s Fear   
1    Watch The Exact Moment Paul Ryan Committed Pol...   
2          Kerry to go to Paris in gesture of sympathy   
3    Bernie supporters on Twitter erupt in anger ag...   
4     The Battle of New York: Why This Primary Matters   
..                                                 ...   
995  Clintons Are Under Multiple FBI Investigations...   
996  First Iraqi Troops Enter Mosul, But Fighting R...   
997  SHOCK VIDEO : Hillary Needs Help Climbing ONE ...   
998  After vowing to end two wars, Obama may leave ...   
999        Climate Engineering And Cryosphere Collapse   

                                                  text label  
0    Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1    Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2    U.S. Secretary of State John F. Kerry said Mon...  REAL  
3    — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4    It's primary day in New York and front-runners...  REAL  
..                                                 ...   ...  
995  Clintons Are Under Multiple FBI Investigations...  FAKE  
996  Military: Goal Is to 'Liberate' Eastern Bank o...  FAKE  
997  SHOCK VIDEO : Hillary Needs Help Climbing ONE ...  FAKE  
998  President Obama’s decision to expand the U.S. ...  REAL  
999  geoengineeringwatch.org \nGlobal climate engin...  FAKE  

[1000 rows x 3 columns]

### EXTRACTING THE DEPENDENT AND INDEPENDENT VARIABLE

In [10]:
x = fake.iloc[:,:-1].values ##IN X WE ARE STORING THE INDEPENDENT VARIABLE WHICH WILL CONSISTS ALL THE EXCEPT THE LAST COLUMN
y = fake.iloc[:,-1].values ##IN Y WE ARE EXTRACTING THE DEPENDENT VARIABLE

### DISPLAYING ALL THE INDEPENDENT VARIABLE

In [11]:
x[0]

array(['You Can Smell Hillary’s Fear',
       'Daniel Greenfield, a Shillman Journalism Fellow at the Freedom Center, is a New York writer focusing on radical Islam. \nIn the final stretch of the election, Hillary Rodham Clinton has gone to war with the FBI. \nThe word “unprecedented” has been thrown around so often this election that it ought to be retired. But it’s still unprecedented for the nominee of a major political party to go war with the FBI. \nBut that’s exactly what Hillary and her people have done. Coma patients just waking up now and watching an hour of CNN from their hospital beds would assume that FBI Director James Comey is Hillary’s opponent in this election. \nThe FBI is under attack by everyone from Obama to CNN. Hillary’s people have circulated a letter attacking Comey. There are currently more media hit pieces lambasting him than targeting Trump. It wouldn’t be too surprising if the Clintons or their allies were to start running attack ads against the FBI. \nThe F

In [12]:
y[0]

'FAKE'

### VECTORIZING THE BODY OF THE INDEPENDENT VARIABLE AND CONVERTING IT INTO A DENSE MATRIX

In [13]:
from sklearn.feature_extraction.text import CountVectorizer ##WORD COUNT
cv = CountVectorizer(max_features=5000)
mat_body = cv.fit_transform(x[:,1]).todense()

In [14]:
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 3, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### VECTORIZING THE HEAD OF THE INDEPENDENT VARIABLE AND COVERTING IT INTO A DENSE MATRIX

In [15]:
cv_head = CountVectorizer(max_features=5000) ##WORD COUNT
mat_head = cv_head.fit_transform(x[:,1]).todense()

In [16]:
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 3, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### STACKING THE MATRICES OVER EACH OTHER

In [17]:
x_mat = np.hstack((mat_head,mat_body))

In [18]:
x_mat

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 3, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### DIVIDING THE MATRIX INTO TRAIN AND TEST SETS USING TRAIN_TEST_SPLIT

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_mat,y,test_size=0.3, random_state=0) ##0.3 MEANS 30% OF THE DATA WILL BE ON THE TEST SET

#### BUILD THE DECISION_TREE_CLASSIFIER MODEL

In [20]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion='entropy')
dtc.fit(x_train,y_train) ##FITTING THE MODEL OVER THE TRAINING SET
y_pred = dtc.predict(x_test) ##PREDICTING THE VALUES ON TOP OF THE TEST SET

In [21]:
y_pred

array(['FAKE', 'REAL', 'REAL', 'REAL', 'FAKE', 'REAL', 'FAKE', 'FAKE',
       'REAL', 'REAL', 'REAL', 'REAL', 'REAL', 'REAL', 'REAL', 'REAL',
       'REAL', 'FAKE', 'REAL', 'FAKE', 'FAKE', 'FAKE', 'REAL', 'REAL',
       'REAL', 'FAKE', 'FAKE', 'FAKE', 'FAKE', 'REAL', 'REAL', 'FAKE',
       'FAKE', 'REAL', 'FAKE', 'FAKE', 'REAL', 'REAL', 'REAL', 'REAL',
       'REAL', 'FAKE', 'REAL', 'REAL', 'REAL', 'FAKE', 'REAL', 'REAL',
       'REAL', 'FAKE', 'REAL', 'FAKE', 'REAL', 'REAL', 'FAKE', 'REAL',
       'REAL', 'REAL', 'REAL', 'FAKE', 'REAL', 'FAKE', 'FAKE', 'FAKE',
       'REAL', 'REAL', 'FAKE', 'FAKE', 'REAL', 'FAKE', 'REAL', 'REAL',
       'FAKE', 'REAL', 'FAKE', 'REAL', 'REAL', 'FAKE', 'FAKE', 'FAKE',
       'FAKE', 'FAKE', 'FAKE', 'REAL', 'FAKE', 'REAL', 'REAL', 'FAKE',
       'FAKE', 'REAL', 'REAL', 'FAKE', 'REAL', 'FAKE', 'FAKE', 'REAL',
       'FAKE', 'REAL', 'FAKE', 'REAL', 'REAL', 'REAL', 'REAL', 'REAL',
       'FAKE', 'FAKE', 'FAKE', 'REAL', 'FAKE', 'FAKE', 'FAKE', 'REAL',
      

#### BUILDING A CONFUSION MATRIX

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred) ##LEFT DIAGONAL GIVES ALL THE CORRECTLY PREDICTED VALUES & RIGHT DIAGONAL GIVES THE INCORRECTLY PREDICTED VALUES

array([[103,  53],
       [ 43, 101]], dtype=int64)

#### ACCURACY OF THE DECISION TREE MODEL

In [23]:
Accuracy=((103+101)/(103+101+53+43))*100
print(Accuracy,"%")

68.0 %
